%----------------------------------------------------------------------------------------
%            RESULTS
%----------------------------------------------------------------------------------------

\subsection{Overall}

%----------------------------FIRST FIGURE------------------------------------------------

% \subsection*{Overall Prevalence}


%latex.default(object = Overall.tabl[, c(-1, -2)], title = "Group",     file = "", rowname = c("Adults"), colhead = c("Prevalence",         "Cases", "Sample Size"), append = TRUE, table.env = T,     here = T, caption = paste(set_Measure, " among adults in ",         set_Country, ", ", set_Years, sep = ""), label = paste("tab:Overall.tabl",         set_DiseaseF, set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence among adults in Puerto Rico, 2013\label{tab:Overall.tabl.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llll}
\hline\hline
\multicolumn{1}{l}{Group}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases}&\multicolumn{1}{c}{Sample Size}\tabularnewline
\hline
Adults&8.08 (7.26-8.9)&226,897&6,011\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}



%----------------------------------------------------------------------------------------

\begin{itemize}


\item The Coronary heart disease prevalence for the year 2013 among adults in Puerto Rico was 8.08 (7.25-8.90) percent, 
Table \ref{tab:Overall.tabl.Coronary_Heart_Disease.2013}.

\end{itemize}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%                     Definition of matrices for the tables                  %%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\subsection{Socio-demographics}

\begin{itemize}

\item Figure \ref{fig:age.Coronary_Heart_Disease.2013} shows that the coronary heart disease prevalence for the age group of
65+
was higher when compared with the other groups.

\item Adults in the age group of 45-54, 55-64, 65+ had 3.21 times more possibility, 4.62 times more possibility, 4.86 times more possibility, respectively, of reporting coronary heart disease prevalence when compared with the 18-24 group. This differences were significant (p-value $<$ 0.05). See Table \ref{tab:age.Coronary_Heart_Disease.2013}.


\end{itemize}


\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults by age group, 
2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013ageg2-1} 

}



\end{knitrout}
\label{fig:age.Coronary_Heart_Disease.2013}
\end{figure}

%latex.default(tabl.ageg2, title = "Variables", file = "", append = TRUE,     rgroup = "Age group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by age group,",         set_Years, sep = " "), label = paste("tab:age", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults by age group, 2013\label{tab:age.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Age group}&&&&&\tabularnewline
~~18-24&1.40 (0.39-2.42)& 5,320&1.00&0.00&1.00\tabularnewline
~~25-34&3.63 (1.97-5.29)&17,672&1.95&0.55&0.22\tabularnewline
~~35-44&5.07 (3.29-6.85)&24,453&2.15&0.53&0.14\tabularnewline
~~45-54&8.26 (6.17-10.3)&39,988&3.21&0.51&0.02\tabularnewline
~~55-64&13.0 (10.5-15.5)&56,793&4.62&0.52&0.00\tabularnewline
~~65+&15.2 (13.1-17.3)&82,670&4.86&0.54&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


\newpage
\begin{itemize}

\item Figure \ref{fig:sex.Coronary_Heart_Disease.2013} shows that males had a \ifthenelse{
697 < 905}{lower}{higher}
coronary heart disease prevalence when compared with females.

%\item Table \ref{tab:sex} shows the estimates for persons living with set_Disease in 
%set_Country with it 95\% confidence interval.

\item Among adults, females had 24\% more possibility of reporting coronary heart disease prevalence when compared with males. This difference was not significant (p-value $>$ 0.05). See Table \ref{tab:sex.Coronary_Heart_Disease.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults by sex group, 
2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013sex-1} 

}



\end{knitrout}
\label{fig:sex.Coronary_Heart_Disease.2013}
\end{figure}

%latex.default(tabl.sex, title = "Variables", file = "", append = TRUE,     rgroup = "Sex group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by sex group,",         set_Years, sep = " "), label = paste("tab:sex", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults by sex group, 2013\label{tab:sex.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Sex group}&&&&&\tabularnewline
~~Males&6.97 (5.76-8.17)& 91,562&1.00&0.00&1.00\tabularnewline
~~Females&9.05 (7.92-10.1)&135,334&1.24&0.14&0.13\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%###################### educag ####################
\newpage
\begin{itemize}

\item When comparing by education level, those with
some high school
have the highest coronary heart disease prevalence. A 12\% of the coronary heart disease prevalence patients had some high school.
(Figure \ref{fig:edu.Coronary_Heart_Disease.2013}).

\item 
When observing the adjusted odds ratio the group high school graduate had 27\% less possibility of reporting coronary heart disease prevalence than the comparison group (Some High School).
This difference was not significant (p-value $>$ 0.05).  Data shown in Table \ref{tab:edu.Coronary_Heart_Disease.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults by education levels, 
         2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013educag-1} 

}



\end{knitrout}
 \label{fig:edu.Coronary_Heart_Disease.2013}
\end{figure}

%latex.default(tabl.educag3, title = "Variables", file = "", append = TRUE,     rgroup = "Education group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by education levels,",         set_Years, sep = " "), label = paste("tab:edu", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults by education levels, 2013\label{tab:edu.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Education group}&&&&&\tabularnewline
~~Some High School&12.9 (10.8-15.0)&102,745&1.00&0.00&1.00\tabularnewline
~~High School Graduate&7.33 (5.82-8.83)& 53,421&0.73&0.17&0.08\tabularnewline
~~Some University&5.35 (4.06-6.63)& 37,930&0.73&0.20&0.13\tabularnewline
~~University Graduate&5.74 (4.50-6.97)& 32,801&0.81&0.21&0.35\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
 
 \newpage
\begin{itemize}

\item Figure \ref{fig:income.Coronary_Heart_Disease.2013} shows that adults whose annual household income is 
$<$15k, have a coronary heart disease prevalence higher than the other income groups.

\item Those in the range of 25k-$<$35k had 44\% less possibility of reporting coronary heart disease than those whose annual income is less than \$ 14,999. This difference was significant (p-value $<$ 0.05).  For further information, refer to Table \ref{tab:income.Coronary_Heart_Disease.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults by household income levels, 
         2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013incomg-1} 

}



\end{knitrout}
 \label{fig:income.Coronary_Heart_Disease.2013}
\end{figure}

%latex.default(tabl.incomg, title = "Variables", file = "", append = TRUE,     rgroup = "Income group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by income levels,",         set_Years, sep = " "), label = paste("tab:income", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults by income levels, 2013\label{tab:income.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Income group}&&&&&\tabularnewline
~~\textless15k&9.91 (8.49-11.3)&119,278&1.00&0.00&1.00\tabularnewline
~~15k-\textless25k&7.22 (5.49-8.95)& 46,436&0.96&0.18&0.85\tabularnewline
~~25k-\textless35k&4.13 (2.20-6.05)&  8,298&0.56&0.28&0.04\tabularnewline
~~35k-\textless50k&4.40 (2.36-6.45)&  6,424&0.73&0.30&0.31\tabularnewline
~~50+k&3.78 (2.01-5.55)&  5,385&0.62&0.32&0.14\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

%%%%%%%%%%%%%%%%% Marial Status %%%%%%%%%%%%%%%%%%%%%%%%%
 \newpage
\begin{itemize}

\item Adults who were 
widowed at the time of the interview, had the highest coronary heart disease among marital status. Refer to figure \ref{fig:marital.Coronary_Heart_Disease.2013}.

\item Those who were separated had 33\% less possibility of having coronary heart disease prevalence when compared with those who responded being married. This difference was not significant (p-value $>$ 0.05). Refere to Table \ref{tab:marital.Coronary_Heart_Disease.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults by marital status,
         2013}
\label{fig:marital.Coronary_Heart_Disease.2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013marital2-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.marital, title = "Variables", file = "", append = TRUE,     rgroup = "Marital group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by marital status,",         set_Years, sep = " "), label = paste("tab:marital", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults by marital status, 2013\label{tab:marital.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Marital group}&&&&&\tabularnewline
~~Married&9.53 (8.20-10.8)&103,211&1.00&0.00&1.00\tabularnewline
~~Divorced&8.48 (6.38-10.5)& 44,652&0.84&0.18&0.35\tabularnewline
~~Widowed&14.7 (11.3-18.2)& 43,729&1.00&0.20&0.97\tabularnewline
~~Separated&5.35 (2.72-7.98)& 12,823&0.67&0.28&0.17\tabularnewline
~~Never Married&2.83 (1.59-4.07)& 13,924&0.70&0.27&0.21\tabularnewline
~~Unmarried Couple&5.20 (3.04-7.36)&  8,558&0.88&0.28&0.66\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
%%%%%%%%%%%%%%%%%% employment status %%%%%%%%%%
 \newpage
\begin{itemize}


\item Those adults who were 
unable to work at the moment of the interview, had the highest coronary heart disease prevalence (Figure \ref{fig:employ.Coronary_Heart_Disease.2013}).

\item Adults who were unable to work had 3.36 times more possibility of having coronary heart disease prevalence when compared with those who responded being employed. This difference was significant (p-value $<$ 0.05). 
Data shown in Table \ref{tab:employ.Coronary_Heart_Disease.2013}.

%\item Those who are rownames(t.asma.current.socio)[24], 
%rownames(t.asma.current.socio)[25], rownames(t.asma.current.socio)[26] or,
%rownames(t.asma.current.socio)[27] have the same set_Measure in statistical terms.

\end{itemize}

\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults by employment status, 
         2013}
\label{fig:employ.Coronary_Heart_Disease.2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013employ-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.emplrec2, title = "Variables", file = "",     append = TRUE, rgroup = "Employment status", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, " among adults by employment status,",         set_Years, sep = " "), label = paste("tab:employ", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults by employment status, 2013\label{tab:employ.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Employment status}&&&&&\tabularnewline
~~Employed&3.98 (3.03-4.92)& 5,320&1.00&0.00&1.00\tabularnewline
~~Out of work&5.39 (3.09-7.70)&17,672&1.15&0.30&0.64\tabularnewline
~~Homework&10.5 (8.34-12.7)&24,453&1.41&0.24&0.16\tabularnewline
~~Student&0.72 (0.00-1.54)&39,988&0.19&1.12&0.15\tabularnewline
~~Retired&12.8 (10.5-15.1)&56,793&1.50&0.24&0.09\tabularnewline
~~Unable to work&22.0 (17.4-26.5)&82,670&3.36&0.24&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%%%%%%%%%%%%%%%% HRQOL %%%%%%%%%%%%%%%%%%%%%%%%%
 \newpage
\subsection{Health related quality of life}


 \begin{itemize}

\item Figure \ref{fig:fairpoor.Coronary_Heart_Disease.2013} shows that coronary heart disease prevalence  was 
\ifthenelse{
 363 < 
  1625}{higher}{lower} in persons who perceive their health has fair / poor,
than those who claim to have a very good health.

\item Adults who perceive their health as fair or poor had 41\% more possibility of reporting coronary heart disease prevalence when compared with those who perceived their health as very good. This difference was not significant (p-value $>$ 0.05). Data shown in Table \ref{tab:fairpoor.Coronary_Heart_Disease.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults according to health perception,
         2013}
\label{fig:fairpoor.Coronary_Heart_Disease.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013poorh-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.fairpoor, title = "Variables", file = "",     append = TRUE, rgroup = "Health Perception", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, " among adults according to health perception,",         set_Years, sep = " "), label = paste("tab:fairpoor",         set_DiseaseF, set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults according to health perception, 2013\label{tab:fairpoor.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Health Perception}&&&&&\tabularnewline
~~Very Good&3.63 (2.92-4.34)& 65,906&1.00&0.00&1.00\tabularnewline
~~Fair / Poor&16.2 (14.3-18.1)&160,762&1.41&0.25&0.16\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
\newpage

%%%%%%%%%%%%% physical unhealthy %%%%%%%%%%%%
 \newpage
\begin{itemize}

\item Adults who reported being physically unhealthy for 14 days or more in the past 30 days, had an coronary heart disease that was 
\ifthenelse{
 645 >
  1738}{lower}{higher} when compared with 
those who reported being physically unhealthy for less than 13 days in the last 30 days.

%\item Table \ref{tab:phys} shows the estimations of the set_Measure.

\item Adults who felt physically impaired for 14 days or more had 10\% more possibility of reporting having coronary heart disease at the moment of the interview, when compared with those who felt physically impaired for 13 days or less (See Table \ref{tab:phys.Coronary_Heart_Disease.2013}).

\end{itemize}

\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults according to physical health perception, 2013}
\label{fig:phys.Coronary_Heart_Disease.2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013physchlcat-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.physhlcat, title = "Variables", file = "",     append = TRUE, rgroup = "Days with physical symptoms", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, "among adults by days with physical symptoms,",         set_Years, sep = " "), label = paste("tab:phys", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence among adults by days with physical symptoms, 2013\label{tab:phys.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Days with physical symptoms}&&&&&\tabularnewline
~~0-13 days&6.45 (5.64-7.25)&154,008&1.00&0.00&1.00\tabularnewline
~~14 or more days&17.3 (14.3-20.3)& 70,991&1.10&0.25&0.68\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%%%%%%%%%%%%%%%%%%%%%%%% Mentally unhelathy %%%%%%%%%%%%%%
 \newpage
\begin{itemize}

\item Coronary heart disease prevalence among adults who reported feeling mentally unhealthy for more than 13 days in the last month was \ifthenelse{680 > 
  1500}{lower}{higher} when compared with their counterpart (Figure \ref{fig:mental.Coronary_Heart_Disease.2013}).

%\item set_Measure for this groups are presented in the Table \ref{tab:mental}.

\item  Adults who felt mentally impaired for 14 or more days had 27\% more possibility of having coronary heart disease prevalence when compared with those who answered 0-13 days. This difference was not significant (p-value $>$ 0.05). (See Table \ref{tab:mental.Coronary_Heart_Disease.2013}).

\end{itemize}

\begin{figure}[H]
\centering
\caption{Coronary heart disease prevalence among adults by days of frequent mental distress, 2013}
\label{fig:mental.Coronary_Heart_Disease.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013mentdist-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.mentdist, title = "Variables", file = "",     append = TRUE, rgroup = "Mentally Unhealthy", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, "among",         set_Population, "by days of frequent mental distress,",         set_Years, sep = " "), label = paste("tab:mental", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence among adults by days of frequent mental distress, 2013\label{tab:mental.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Mentally Unhealthy}&&&&&\tabularnewline
~~0-13 days&6.80 (6.00-7.61)&163,093&1.00&0.00&1.00\tabularnewline
~~14 or more days&15.0 (11.9-18.0)& 58,115&1.27&0.27&0.37\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}



%%%%%%%%%%%%%%%%%%% poorhlcat %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 \newpage
\begin{itemize}

\item A \ifthenelse{
 1079 > 
  1881}{lower}{higher} 
coronary heart disease prevalence was observed among adults who were unable to perform their usual activities for 14 days or more due to physical or mental impairment, when compared with the other group. Refer to Figure \ref{fig:poor.Coronary_Heart_Disease.2013}.



\item Persons who could not conduct their usual daily activities for more than 14 days in the last month had 30\% less possibility of reporting coronary heart disease when compared with those who felt this way for at most 13 days in the last 30.

\end{itemize}

\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults who were unable to conduct usual activities due to physical or mental impediment, 2013}
\label{fig:poor.Coronary_Heart_Disease.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013poor-1} 

}



\end{knitrout}
\end{figure}

%latex.default(tabl.poorhlcat, title = "Variables", file = "",     append = TRUE, rgroup = "Activiy limitation", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, "among",         set_Population, "who were unable to cunduct usual activities due to physical or mental impairment,",         set_Years, sep = " "), label = paste("tab:poor", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence among adults who were unable to cunduct usual activities due to physical or mental impairment, 2013\label{tab:poor.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Activiy limitation}&&&&&\tabularnewline
~~0-13 days&10.7 (9.20-12.3)&106,122&1.00&0.00&1.00\tabularnewline
~~14 or more days&18.8 (14.6-22.9)& 46,551&0.70&0.34&0.32\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%%%%%%%%%%%%%%%%%%%%% unhlthy %%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\begin{itemize}

\item As seen in Figure \ref{fig:unhlthy.Coronary_Heart_Disease.2013}, those adults who felt mentally or physically unhealthy for more than 14 days in the last 30 days, had \ifthenelse{
5>
14}{lower}{higher} 
coronary heart disease prevalence when compared with their counterpart.

%\item The prevalence for those who felt mentally or fisically unhealthy is more than twice of the
%prevalence of those who felt healthy for at least 14 days in the past 30(Table \ref{tab:unhlthy}).

\item Those persons who felt mentally or physically unhealthy for more than 14 days in the last month had 49\% more possibility of reporting coronary heart disease when compared with those who felt mentally or physically unhealthy for at most 13 days in the last 30 days. Data shown in Table \ref{tab:unhlthy.Coronary_Heart_Disease.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Coronary heart disease prevalence among adults by unhealthy days, 2013}
\label{fig:unhlthy.Coronary_Heart_Disease.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Coronary_Heart_Disease/Prevalence/Adult/2013unhealthy-1} 

}



\end{knitrout}
\end{figure}

%latex.default(tabl.unhlthy, title = "Variables", file = "", append = TRUE,     rgroup = "Unhealthy Days", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, "among", set_Population,         "by unhealthy days,", set_Years, sep = " "), label = paste("tab:unhlthy",         set_DiseaseF, set_Years, sep = "."))%
\begin{table}[H]
\caption{Coronary heart disease prevalence among adults by unhealthy days, 2013\label{tab:unhlthy.Coronary_Heart_Disease.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Unhealthy Days}&&&&&\tabularnewline
~~0-13 days&5.95 (5.14-6.76)&127,786&1.00&0.00&1.00\tabularnewline
~~14 or more days&14.9 (12.7-17.2)& 99,110&1.49&0.23&0.08\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


 \section{Remarks}

An estimate of 289,917 
(10.29\%) adult in Puerto Rico had coronary heart disease prevalence as of the period of 2013.
When evaluating by the socio-demographic variables, no specific group has been disproportionately affected with coronary heart disease in age groups, educational level or marital status. With regards to gender the coronary heart disease was 1.24 times higher in women. Although not statistically significant those in the household income range of 35k-50k and those in the range of more than 50k annually, had \ensuremath{-2} and \ensuremath{-1} respectively less possibility of coronary heart disease prevalence that those  in group of those who receive less than 15k annually.

Moving to the health related quality of life measures, the possibility of reporting coronary heart disease prevalence in adults that perceived their health as fair or poor was 1.41 times higher than those who considered their health as good, very good or excellent. The adults who said that they felt physically bad for 14 days or more for the last 30 days had 1.10 times higher possibility of reporting coronary heart disease prevalence than those less than 13 days. In the same manner, adults who felt mentally distressed for 14 days or more in a month had 1.27 times higher possibility of reporting coronary heart disease prevalence than those less than 13 days feeling mentally distressed. From 1.6 million adults who were unable to carry on with their normal activities more than 14 days in a month, 14.9 (12.7-17.2) percent reported coronary heart disease prevalence. 

People who exercise, or are exposed to physical activities reported \ensuremath{-1} \% higher risk of coronary heart disease than those who don't.  Regarding body mass index (BMI), those obese and overweight had \ensuremath{-1}\% and 2\% respectively more possibility of coronary heart disease prevalence than those neither obese nor overweight. The estimation of the coronary heart disease prevalence on smokers was 8.58 (7.68-9.48) percent.  Adults with diabetes were \ensuremath{-1}\5 less likely to have coronary heart disease prevalence than their counterpart.


%\newpage
%\vspace{1cm}

Progress has been made in understanding the burden of coronary heart disease in Puerto Rico. Advancements in the diagnose and treatment of the condition have had considerably improved in the last 20 years, but it is still an uncontrolled condition. The disclosed information is part of the effort of the Puerto Rico coronary heart disease Project to provide an update of the state of coronary heart disease in our country. The report presents information that can aid in the development of public policy, guide changes in the health care system, monitor population coronary heart disease control, enhance educational materials, and guide all efforts to target factors of disparities as a way of reducing the morbidity and mortality associated with coronary heart disease in Puerto Rico.

%Summary tables
\newpage
\section{Summary tables}
In this section we provide a set of summary tables of coronary heart disease among adults Puerto Rico for the years 2013. The tables aggregate all the analysis conducted in this report for an easy to print and carry document for reference, or to be used as an annex for the preparation of other documents such as an application for funds. For the interpretation of each result, please refer to the corresponding section in the document.

\subsection{Adults}

 
%latex.default(object = SocioD.tabl, title = "Variables", file = "",     append = TRUE, rgroup = c("Age group", "Gender", "Escolarity",         "Household income", "Marital status", "Employment status"),     n.rgroup = c(6, 2, 4, 5, 6, 6), table.env = T, longtable = F,     here = T, caption = paste(set_Measure, " among adults by socio-demographic variables,",         set_Years, sep = " "), label = "tab:SocioD.tabl")%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults by socio-demographic variables, 2013\label{tab:SocioD.tabl}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Number}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Age group}&&&&&\tabularnewline
~~18-24&1.40 (0.39-2.42)& 5,320&1.00&0.00&1.00\tabularnewline
~~25-34&3.63 (1.97-5.29)&17,672&1.95&0.55&0.22\tabularnewline
~~35-44&5.07 (3.29-6.85)&24,453&2.15&0.53&0.14\tabularnewline
~~45-54&8.26 (6.17-10.3)&39,988&3.21&0.51&0.02\tabularnewline
~~55-64&13.0 (10.5-15.5)&56,793&4.62&0.52&0.00\tabularnewline
~~65+&15.2 (13.1-17.3)&82,670&4.86&0.54&0.00\tabularnewline
\hline
{\bfseries Gender}&&&&&\tabularnewline
~~Males&6.97 (5.76-8.17)& 91,562&1.00&0.00&1.00\tabularnewline
~~Females&9.05 (7.92-10.1)&135,334&1.24&0.14&0.13\tabularnewline
\hline
{\bfseries Escolarity}&&&&&\tabularnewline
~~Some High School&12.9 (10.8-15.0)&102,745&1.00&0.00&1.00\tabularnewline
~~High School Graduate&7.33 (5.82-8.83)& 53,421&0.73&0.17&0.08\tabularnewline
~~Some University&5.35 (4.06-6.63)& 37,930&0.73&0.20&0.13\tabularnewline
~~University Graduate&5.74 (4.50-6.97)& 32,801&0.81&0.21&0.35\tabularnewline
\hline
{\bfseries Household income}&&&&&\tabularnewline
~~\textless15k&9.91 (8.49-11.3)&119,278&1.00&0.00&1.00\tabularnewline
~~15k-\textless25k&7.22 (5.49-8.95)& 46,436&0.96&0.18&0.85\tabularnewline
~~25k-\textless35k&4.13 (2.20-6.05)&  8,298&0.56&0.28&0.04\tabularnewline
~~35k-\textless50k&4.40 (2.36-6.45)&  6,424&0.73&0.30&0.31\tabularnewline
~~50+k&3.78 (2.01-5.55)&  5,385&0.62&0.32&0.14\tabularnewline
\hline
{\bfseries Marital status}&&&&&\tabularnewline
~~Married&9.53 (8.20-10.8)&103,211&1.00&0.00&1.00\tabularnewline
~~Divorced&8.48 (6.38-10.5)& 44,652&0.84&0.18&0.35\tabularnewline
~~Widowed&14.7 (11.3-18.2)& 43,729&1.00&0.20&0.97\tabularnewline
~~Separated&5.35 (2.72-7.98)& 12,823&0.67&0.28&0.17\tabularnewline
~~Never Married&2.83 (1.59-4.07)& 13,924&0.70&0.27&0.21\tabularnewline
~~Unmarried Couple&5.20 (3.04-7.36)&  8,558&0.88&0.28&0.66\tabularnewline
\hline
{\bfseries Employment status}&&&&&\tabularnewline
~~Employed&3.98 (3.03-4.92)& 5,320&1.00&0.00&1.00\tabularnewline
~~Out of work&5.39 (3.09-7.70)&17,672&1.15&0.30&0.64\tabularnewline
~~Homework&10.5 (8.34-12.7)&24,453&1.41&0.24&0.16\tabularnewline
~~Student&0.72 (0.00-1.54)&39,988&0.19&1.12&0.15\tabularnewline
~~Retired&12.8 (10.5-15.1)&56,793&1.50&0.24&0.09\tabularnewline
~~Unable to work&22.0 (17.4-26.5)&82,670&3.36&0.24&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 

 
%latex.default(object = hrqol.tabl, title = "Variables", file = "",     append = TRUE, rgroup = c("Health perception", "Physical unhealthy",         "Mental unhealthy", "Activity limitation", "Physical and mental unhealthy"),     n.rgroup = c(2, 2, 2, 2, 2), rowname = c("Very Good", "Fair / Poor",         rep(c("0-13 days", "14 or more days"), 4)), table.env = T,     here = T, caption = paste(set_Measure, " among adults by health related quality of life variables,",         set_Years, sep = " "), label = "tab:hrqol.tabl")%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults by health related quality of life variables, 2013\label{tab:hrqol.tabl}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Number}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Health perception}&&&&&\tabularnewline
~~Very Good&3.63 (2.92-4.34)& 65,906&1.00&0.00&1.00\tabularnewline
~~Fair / Poor&16.2 (14.3-18.1)&160,762&1.41&0.25&0.16\tabularnewline
\hline
{\bfseries Physical unhealthy}&&&&&\tabularnewline
~~0-13 days&6.45 (5.64-7.25)&154,008&1.00&0.00&1.00\tabularnewline
~~14 or more days&17.3 (14.3-20.3)& 70,991&1.10&0.25&0.68\tabularnewline
\hline
{\bfseries Mental unhealthy}&&&&&\tabularnewline
~~0-13 days&6.80 (6.00-7.61)&163,093&1.00&0.00&1.00\tabularnewline
~~14 or more days&15.0 (11.9-18.0)& 58,115&1.27&0.27&0.37\tabularnewline
\hline
{\bfseries Activity limitation}&&&&&\tabularnewline
~~0-13 days&10.7 (9.20-12.3)&106,122&1.00&0.00&1.00\tabularnewline
~~14 or more days&18.8 (14.6-22.9)& 46,551&0.70&0.34&0.32\tabularnewline
\hline
{\bfseries Physical and mental unhealthy}&&&&&\tabularnewline
~~0-13 days&5.95 (5.14-6.76)&127,786&1.00&0.00&1.00\tabularnewline
~~14 or more days&14.9 (12.7-17.2)& 99,110&1.49&0.23&0.08\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 

 
%latex.default(object = riskComo.tabl, title = "Variables", file = "",     append = TRUE, rgroup = c("Exercise", "BMI", "Tobacco Use",         "Any chronic condition"), n.rgroup = c(2, 3, 2, 2), rowname = c("Yes",         "No", "Neither", "Overweight", "Obese", "Yes", "No",         "Yes", "No"), table.env = T, here = T, caption = paste(set_Measure,         " among adults by risk and comorbidity variables,", set_Years,         sep = " "), label = "tab:riskComo.tabl")%
\begin{table}[H]
\caption{Coronary heart disease prevalence  among adults by risk and comorbidity variables, 2013\label{tab:riskComo.tabl}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Number}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Exercise}&&&&&\tabularnewline
~~Yes&6.59 (5.50-7.67)& 94,547&1.00&0.00&1.00\tabularnewline
~~No&9.88 (8.60-11.1)&131,061&1.14&0.16&0.40\tabularnewline
\hline
{\bfseries BMI}&&&&&\tabularnewline
~~Neither&5.51 (0.54-10.4)& 3,580&1.00&0.00&1.00\tabularnewline
~~Overweight&5.93 (4.60-7.27)&49,519&1.69&0.69&0.44\tabularnewline
~~Obese&8.48 (7.11-9.85)&88,441&1.93&0.68&0.33\tabularnewline
\hline
{\bfseries Tobacco Use}&&&&&\tabularnewline
~~Yes&8.58 (7.68-9.48)&213,615&1.00&0.00&1.00\tabularnewline
~~No&4.01 (2.21-5.82)& 11,994&0.52&0.35&0.06\tabularnewline
\hline
{\bfseries Any chronic condition}&&&&&\tabularnewline
~~Yes&0 (0-0)&      0&1.00&0.00&1.00\tabularnewline
~~No&35.5 (32.5-38.5)&226,897&5403&0.24&0\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
 