---
title: "CNCD Report Introduction"
author: "José A. Bartolomei-Díaz, PhD - Outcome Project"
date: "March 23, 2015"
header-includes:
   - \usepackage{setspace}
   - \doublespacing
output:
  pdf_document:
    keep_tex: true
bibliography: /home/surfprjab/Dropbox/Puerto_Rico_Chronic_Report/References/ChronReport.bib
csl: /home/surfprjab/Dropbox/Puerto_Rico_Chronic_Report/References/csl_Reference_Style/apa6th.csl
---


\subsection{Worldwide Problem}

Chronic noncommunicable diseases (CNCDs) are the leading cause of death in the world and affect people of all demographic characteristics (ex., age, gender, income, etc). By 2020 it was estimated that 157 million people worldwide will have one ore more chronic diseases [@anderson2010chronic]. The World Health Organization (WHO) has estimated that CNDCs were responsible for 38 million (68%) of the world’s 56 million deaths in 2012. More than 40% of these deaths (16 million) were premature, or occurred among those aged 70 years or less [@world2014draft]. Based on the 2014 WHO Noncommunicable Diseases Country Profile, of the thirty-eight million people who die each year from CNCDs, the principle causes are cardiovascular diseases, cancers, chronic respiratory diseases, and diabetes, making these the four most common noncommunicable diseases worldwide [@ncdWorldProf2014].  Over 14 million deaths from CNCDs occur between the ages of 30 and 70, of which 85% are in developing countries. According to the United States (US) National Health Interview Survey, it was estimated that approximately half (117 million), or 1 in 4 US adults, have at least one of the 10 chronic conditions examined in this study [@ward2014peer]. CNCDs not only carry a threat of premature death but can also affect a person’s physical and mental health, their social life, and employment status in many different ways (Anderson, 2010). [@anderson2010chronic].

How do we define an CNCD? Generally CNCDs are those diseases characterized by an uncertain etiology, multiple risk factors, a long latency period, a prolonged course of disease, are noncontagious in origin, and can cause functional impairment, disability, or an incurable condition [@remington2010chronic]. Various factors could be leading to the recent increase in CNCDs. First, advances in medical science and technology are being used to treat acute disease and maintain a higher level of health and functionality, which results in an increased number of people surviving with chronic conditions. Second, technologies are becoming increasingly successful at making better and more timely diagnoses. Third, the increasing prevalence of chronic conditions can be attributed to our aging society, wherein older age increases the probability of having one or more of these conditions [@anderson2010chronic].

Chronic diseases have important shared features that, if well understood, can aid in planning and implementing public health strategies such as preventive or epidemiological surveillance activities.
 
These features include the fact that [@world2005steps] epidemics take decades to become fully established, they have their origin at young ages, and they require a long term systematic approach to treatment.  Given their long duration, there are multiple opportunities for prevention.  In order to take advantage of these prevention opportunities, health services must integrate their responses to these diseases by developing concerted strategies to reduce the impact of prevalent chronic disease and to reduce the emergence of new cases as much as possible.

\subsection{Chronic Condition Definitions}

This section define the CNCDs that will presented in this report.

- **Asthma:** A common inflammatory disease of the lungs characterized by episodic airway obstruction caused by extensive narrowing of the bronchi and bronchioles. This narrowing is caused by smooth muscle spasms, edema of the mucosa, and the presence of mucus in the airway resulting from an immunologic reaction which can be induced by allergies, irritants, infection, stress, and other factors in a genetically predisposed individual. Common symptoms of asthma include wheezing, coughing, and shortness of breath.

- **Cardiovascular disease (CVD)** a group o f diseases involving the heart, blood vessels, or the poor blood supply resulting from a diseased vascular supply. Among the most important types of CVD are atherosclerosis, rheumatic heart disease, and vascular inflammation. Cardiovascular diseases are a major cause of health problems and death in developed countries [@Dictionary.com2015Britanica]. CVDs that are presented in this report are:

    - **Heart Attack:** Necrosis of a region of the heart muscle caused by an interruption in the supply of blood to the heart, usually as a result of  a coronary artery occlusion resulting from coronary artery disease. Symptoms typically include sudden, crushing chest pain, nausea, and sweating. Characteristic changes in the electrocardiogram are used to diagnose heart attacks. Also called myocardial infarction. 
  
    - **Angina:** A severe constricting pain, especially angina pectoris.
  
    - **Stroke:** A sudden loss of brain function caused by a blockage or rupture of a blood vessel in the brain, resulting in necrosis of brain tissue (called a cerebral infarction) and characterized by loss of muscular control, weakening or loss of sensation or consciousness, dizziness, slurred speech, or other symptoms that vary with the extent and severity of brain damage. Also called cerebrovascular accident. 

- **Diabetes:**  Any of several metabolic disorders marked by excessive discharge of urine and persistent thirst, especially one of the two types of diabetes mellitus.

- **Diabetes Mellitus:** A severe, chronic form of diabetes caused by insufficient pro- duction of insulin and resulting in abnormal metabolism of carbohydrates, fats, and proteins. The disease typically appears in childhood or adolescence and is charac- terized by increased sugar levels in the blood and urine, excessive thirst, frequent urination, acidosis, and wasting. Also called insulin-dependent diabetes, type I dia- betes is a mild form of diabetes that typically appears first in adulthood and is exacerbated by obesity and an inactive lifestyle. This disease often has no symptoms, is usually diagnosed by tests that indicate glucose intolerance, and is treated with changes in diet and an exercise regimen. Type I diabetes is also called adult-onset diabetes, late- onset diabetes, non-insulin-dependent diabetes, type II diabetes.

The diseases definitions were obtained from The American Heritage® Science Dictionary via the Dictionary.com website [@Dictionary.com2015]


\subsection{Risk Factors}

Based on the dictionary of epidemiology, “A risk factor is an aspect of personal behavior or lifestyle, an environmental exposure, or an inborn or inherited characteristic that, on the basis of scientific evidence, is known to be associated with meaningful health-related conditions(s). A risk factor can be modified through intervention, thereby reducing the probability of occurrence of a disease” [@porta2014dictionary]. 

More simply put, a ‘risk factor’ refers to any attribute, characteristic or exposure of an individual which increases the likelihood of developing a chronic noncommunicable disease [@world2005steps].

Interestingly, four behavioral risk factors are associated with the CNCDs mentioned: tobacco use, excessive alcohol consumption, poor diet, and lack of physical activity [@hunter2013noncommunicable]. These are risk factors themselves for biological risk factor determinants of chronic diseases: overweight and obesity, high blood pressure, high blood glucose and abnormal blood lipids [@world2005steps]. There is evidence that a reduction in these risk factors and access to treatment can reduce the mortality and morbidity associated with CNCDs [@ford2011proportion; @sytkowski1990changes].

\subsection{Economic Impact}

CNCDs affect economies, health systems, households and individuals through a range of drivers such as reduced labor productivity, higher medical treatment costs, and lost savings [@nikolic2011chronic].  In the next 10 years, China, India and the United Kingdom are projected to lose $558 billion, $237 billion and $33 billion, respectively, in national income as a result of heart disease, stroke and diabetes due in part to reduced economic productivity [@daar2007grand]. 
@anderson2010chronic stated that United States spent 85 percent of the health care dollar on people with chronic conditions. Ignoring the importance of planning and implementing activities to reduce the risk of chronic diseases could cause an estimated production loss, among 23 low and middle income countries, of US $84 billion due to heart disease, stroke, and diabetes alone between 2006 and 2015 [@abegunde2007burden]. 

Economic decline occurs because an increase in persons with chronic diseases leads to a reduction in productivity and competitiveness, fiscal pressures, health outcomes, poverty, inequity and opportunity loss  [@nikolic2011chronic].

The public health focus for CNCDs has been on treatment rather than prevention.  However, the economic impact of CNCDs can be most greatly reduced and quality of life can be most greatly improved through preventive rather than treatment measures [@jamison2006disease].  In fact, evidence shows that millions of deaths can be averted and economic losses can be reduced by billions of dollars if added focus is put on prevention [@bloom2012global]. 

\subsection{The Role of Epidemiological Surveillance}

An epidemiological surveillance system is a systematic and continuous collection, analysis and interpretation of data, closely integrated with the timely and coherent dissemination of results to those who have the right to know so that actions can be taken  [@porta2014dictionary].  

Strong country-level surveillance and monitoring systems are critical in appropriately addressing non-communicable diseases. These systems can be strengthened by conducting surveys that are integrated into existing national health information systems, include monitoring exposure to risk factors, outcomes, social and economic determinants of health, and health system responses  [@assembly2011political]. 

A key component of any national strategy to address this challenge is to quantify and monitor non-communicable diseases and their determinants through sustainable surveillance schemes that are integrated into the national information system [@alwan2010monitoring].

It is vital to recognize that surveillance systems are a network of people and activities that form complex processes. Over time, these systems are used to identify changes in the nature and extent of health problems and the effectiveness of public health interventions [@rothman2008modern]. 

Functional epidemiological surveillance systems allow health officers to establish priorities to direct resources for prevention activities.  More specifically, they can be used to: (1) estimate the magnitude of a health problem in the population at risk; (2) understand the natural history of disease or injury; (3) detect outbreaks or epidemics; (4) document the distribution and spread of a health event; (5) test hypotheses about etiology; (6) evaluate control strategies; (7) monitor changes in infectious agents; (8) monitor isolation activities; (9) detect changes in health practice; assess the quality of health care; (11) assess the safety of drugs of procedures; (12) identify research needs and to facilitate epidemiological and laboratory research [@teutsch2000principles].  

Following the Political Declaration on Noncommunicable Diseases (CNCDs) adopted by the UN General Assembly in 2011, WHO developed a global monitoring framework toenable global tracking of progress in preventing and controlling major noncommunicable diseases - cardiovascular disease, cancer, chronic lung diseases and diabetes - and their key risk factors. All countries can benefit from a comprehensive response to attaining the voluntary global targets presented in the WHO report.

\begin{itemize}
\item Global target 1: A 25\% relative reduction in overall mortality from cardiovascular diseases, cancer, diabetes or chronic respiratory diseases

\item Global target 2: At least 10\% relative reduction in the harmful use of alcohol as appropriate, within the national context

\item Global target 3: A 10\% relative reduction in the prevalence of insufficient physical activity 

\item Global target 4: A 30\% relative reduction in the mean population intake of salt /sodium

\item Global target 5: A 30\% relative reduction in prevalence of current tobacco use in persons aged 15+ years 

\item Global target 6: A 25\% relative reduction in the prevalence of high blood pressure, or at least maintaining (and not surpassing) the prevalence of high blood pressure, according to national circumstances 

\item Global target 7: Halt the rise in diabetes and obesity 

\item Global target 8:At least 50\% of eligible people receiving drug therapy and counseling (including glycaemic control) to prevent heart attacks and strokes.

\item Global target 9: An 80\% availability of the affordable basic technologies and es- sential medicines, including generics, required to treat major noncommunicable dis- eases in both public and private facilities
 
\end{itemize}


Given the evidence, the immense public health burden that CNCDs impose on society are expected to lead to an emergence of advanced public health interventions. Surveillance should continue to be implemented to monitor the performance of these strategies and guide future courses of action.

\section{Objective}

The objective of this report is to aid in the advancement of CNCD prevention strategies including surveillance activities by reporting on the prevalence of five important chronic diseases in Puerto Rico based on the most recent data available for Puerto Rico, the 2013 Behavioral Risk Factor Surveillance Survey.

\section{Methods}

\subsection{Data Source}

The BRFSS, administered and supported by the Behavioral Surveillance Branch of the Centers for Disease Control and Prevention (CDC) since 1984, is an on-going cross-sectional health survey system for tracking health conditions and risk behaviors [@mokdad2009behavioral]. The BRFSS is a random-digit-dialing telephone survey with a complex sample design that includes stratification, clustering, and unequal weighting to achieve a representative sample of the adult population 18 years of age or older living in households [@mokdad2009behavioral]. The Puerto Rico Department of Health, under a cooperative agreement with the CDC, first implemented the BRFSS in 1996 and continues conducting it on a yearly basis. The data used for this analysis corresponds to survey year 2013. 

\subsubsection{Survey Question}
Self-reported questions on chronic conditions are included within this survey. The survey questions used are listed below.
		\subsubsection{Diseases}
Has a doctor, nurse, or other health professional EVER told you that you had any of the following? For each, tell me “Yes,” “No,” or you’re “Not sure.”
\begin{itemize}
	\item \textbf{Heart attack:} (Ever told) you that you had a heart attack also called a myocardial infarction?
	\item \textbf{Coronary heart disease:} (Ever told) you had angina or coronary heart disease?
	\item \textbf{Stroke:} (Ever told) you had a stroke?
	\item \textbf{Lifetime asthma:} (Ever told) you had asthma?
	\item \textbf{Current asthma:} Do you still have asthma?
	\item \textbf{Diabetes:} (Ever told) you had diabetes?
\end{itemize}

		\subsubsection{Health Related Quality of Life (HRQOL)}

The Healthy Days Measures are a brief set of survey-based questions designed to assess HRQOL – defined as "perceived physical and mental health over time" [@hennessy1994measuring]. HRQOL is recognized as an important measurement in public health as well as in clinical research and other health-related disciplines [@hagerty2001quality]. Tracking population HRQOL over time helps to identify health disparities, evaluate progress on achieving broad health goals, and inform healthy public policy [@moriarty2003centers].

Five HRQOL measures were obtained from four BRFSS validated questions: (1) "Would you say that in general your health is: excellent, very good, good, fair, or poor?"; (2) "Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?"; (3) "Now thinking about your mental health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?"; and (4)  "During the past 30 days, for about how many days did poor physical or mental health keep you from doing your usual activities, such as self-care, work, or recreation?". Responses to all questions were dichotomized to comply with the CDC recommendations (CDC 2000) and with previous studies  [@ford2003self; @strine2008associations]. 

The responses to the first of these questions were dichotomized as excellent/very good and fair/poor to assess “Individual health perception”. The responses to the remaining questions were divided into two groups, 0-13 days and >14 days, according to the participant’s estimation. The second question provides information about the participant’s “Overall measure of recent physical symptoms”. The third question provides information about “Frequent mental distress”.  Reporting 14 or more days of limitations in activity is referred to as the “Overall measure of perceived disability and productivity”. An additional measure referred as the “Overall of unhealthy days” in the past month was calculated using the number of days in questions (2) and (3), with a logical maximum of 30 days.

\subsubsection{Demographics}
		
Study covariates included socio-demographic indicators such as: age categories (18-24, 25-34, 35-44, 45-54, 55-64, 65-74, and 74 years or older); gender; educational attainment (not high school graduate, high school graduate, some years of college, and college grad- uate); yearly household income (<15,000, 15,000 to 25,000, 25,000 to 35,000, 35,000 to <50,000, and >50,000 US Dollars); marital status (divorced, married, never married, separated, un- married couple, widow); and employment status (for wage, home maker, out of work, retired, self-employed, student, unable to work).
		
\subsection{Statistical Analysis}

 For this report we calculated the following for each of the diseases mentioned: (1) number of cases, prevalence, 95% confidence interval of the prevalence measure, adjusted odds ratio, and standard error and p-value of the adjusted odds ratio. All analyses were conducted using the R environment for statistical computing and pertinent R packages [@R2015].  The complex sampling scheme of the BRFSS survey was taken into account using the survey package[@lumley2012survey].

As this report is intended for a wide variety of audiences we will define statistical and epidemiological terms used through this work. Definitions were obtained from the Dictionary of Epidemiology [@porta2014dictionary]

\begin{itemize}
	\item \textbf{Prevalence:} A measure of disease occurrence that quantifies the proportion of individuals in a population who have a disease or condition. Mathematically it is the total number of individuals who have an attribute or disease at a particular time divided by the population at risk of having the attribute or disease at that time or midway through the period. It could be referred as to the situation of the disease or condition at a specified point in time.
	
	\item \textbf{Odds:} The ratio of the probability of occurrence of an event to that of nonoccurrence, or the ratio of the probability that something is one way to the probability that it is another way.
	
	\item \textbf{Odds Ratio:} The ratio of two odds.
	
	\item \textbf{Statistical Significance:} The probability that the observed or a larger value of a test statistic under the null hypothesis. Often equivalent to the probability or the observed or larger degree of association under the null hypothesis.
	
	\item \textbf{Clinical Significance (Meaningfully):} Difference in effect size considered to be important in medical decisions regardless of the degree of statistical significance.
	
	\item \textbf{Confounding:} The distortion of a measure of the effect of an exposure on an outcome due to the association of the exposure with other factors that influence the occurrence of the outcome. Confounding occurs when all or part of the apparent association between the exposure and outcome is in fact accounted for by other variables that affect the outcome and are not themselves affected by exposure.
	
	\item \textbf{Confidence Interval:} The conventional form of an interval estimate, computed in statistical analyses, based on the theory of frequency probability.  If the underlying statistical model is correct and there is no bias, a confidence interval derived from a valid analysis will, over unlimited repetitions of the study, contain the true parameter with a frequency no less than its confidence level.
\end{itemize}

Simplified, the prevalence indicates how many individuals have the disease of interest (here expressed as per every 100 persons), the 95% confidence intervals measure outcome accuracy, the number of individuals with the outcome aid in resources allocation, the regression modeling strategies asses the risk of particular groups, and the hypothesis testing asseses the statistical significance of the established hypothesis. All Odds Ratios within this work were adjusted using multiple logistic regression models to control for the possibility of confounding. The adjustments were made using the socio-demographic variables stated in this section. From here forward, although it will not always be explicitly stated, all reported ORs will be adjusted for the aforementioned variables.

# Bibliography