
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%                           LOAD LaTeX PACKAGES                              %%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%






%----------------------------------------------------------------------------------------
%            RESULTS
%----------------------------------------------------------------------------------------
\subsubsection{Overall}

%----------------------------FIRST FIGURE------------------------------------------------



%latex.default(object = Overall.tabl[, c(-1, -2)], title = "Group",     file = "", rowname = c("Adults"), colhead = c("Prevalence", "Cases", "Sample Size"), append = TRUE, table.env = T,     here = T, caption = paste(set_Measure, " among adults in ",         set_Country, ", ", set_Years, sep = ""), label = paste("tab:Overall.tabl",         set_DiseaseF, set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence among adults in Puerto Rico, 2013\label{tab:Overall.tabl.Asthma.2013}} 
\begin{center}
\begin{tabular}{llll}
\hline\hline
\multicolumn{1}{l}{Group}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases}&\multicolumn{1}{c}{Sample Size}\tabularnewline
\hline
Adults&10.29 (9.27-11.32)&289,917&6,011\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}



%----------------------------------------------------------------------------------------

\begin{itemize}


\item The current asthma prevalence for the year 2013 among adults in Puerto Rico was 10.2 (9.26-11.3) percent and the estimated number of cases was 289,917, Table \ref{tab:Overall.tabl.Asthma.2013}.

\end{itemize}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%                     Definition of matrices for the tables                  %%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\subsubsection{Socio-demographics}

\begin{itemize}

\item Figure \ref{fig:age.Asthma.2013} shows that the current asthma prevalence for the age group of
18-24
was higher than the other age groups. The differences were not statistically significant (p-value $>$ 0.05). \ref{tab:age.Asthma.2013}

\item Adults in the age group of 25-34, 35-44, 45-54, 55-64, and 65+ had 50\%, 57\%, 55\%, 52\%, and 72\% lower possibility respectively of reporting current asthma prevalence when compared with the 18-24 age group. After controlling for other socio-demographic variables this differences were significant (p-value $<$ 0.05). See Table \ref{tab:age.Asthma.2013}.


\end{itemize}


\begin{figure}[H]
\caption{Current asthma prevalence among adults by age group, 
2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013ageg2-1} 

}



\end{knitrout}
\label{fig:age.Asthma.2013}
\end{figure}

%latex.default(tabl.ageg2, title = "Variables", file = "", append = TRUE,     rgroup = "Age group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by age group,",         set_Years, sep = " "), label = paste("tab:age", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence  among adults by age group, 2013\label{tab:age.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Age group}&&&&&\tabularnewline
~~18-24&13.3 (9.78-16.9)&50,633&1.00&0.00&1.00\tabularnewline
~~25-34&8.60 (5.62-11.5)&42,042&0.50&0.32&0.03\tabularnewline
~~35-44&9.81 (7.40-12.2)&47,193&0.43&0.32&0.01\tabularnewline
~~45-54&9.71 (7.50-11.9)&47,072&0.45&0.33&0.01\tabularnewline
~~55-64&12.4 (9.93-14.9)&54,507&0.48&0.35&0.04\tabularnewline
~~65+&8.85 (7.39-10.3)&48,469&0.28&0.39&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


\newpage
\begin{itemize}

\item Figure \ref{fig:sex.Asthma.2013} shows that males had a \ifthenelse{
701 < 1318}{lower}{higher}
current asthma prevalence than females.

%\item Table \ref{tab:sex} shows the estimates for persons living with set_Disease in 
%set_Country with it 95\% confidence interval.

\item Among adults, females had a 2.22 times more possibility of reporting asthma compared to males. This difference was significant (p-value $<$ 0.05). See Table \ref{tab:sex.Asthma.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Current asthma prevalence among adults by gender, 
2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013sex-1} 

}



\end{knitrout}
\label{fig:sex.Asthma.2013}
\end{figure}

%latex.default(tabl.sex, title = "Variables", file = "", append = TRUE,     rgroup = "Sex group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by sex group,",         set_Years, sep = " "), label = paste("tab:sex", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence among adults by sex group, 2013\label{tab:sex.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Sex group}&&&&&\tabularnewline
~~Males&7.01 (5.54-8.47)& 92,596&1.00&0.00&1.00\tabularnewline
~~Females&13.1 (11.7-14.6)&197,321&2.22&0.15&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%###################### educag ####################
\newpage
\begin{itemize}

\item When comparing education level, those with
Some University
have the highest prevalence of asthma, reported to be 12\%.
(Figure \ref{fig:edu.Asthma.2013}).

\item 
When observing the adjusted odds ratio, the University Graduate group had 20\% lower possibility of reporting currently having asthma than the reference group (Some High School).
This difference was not significant (p-value $>$ 0.05).  Data shown in Table \ref{tab:edu.Asthma.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Current asthma prevalence among adults by education level, 
         2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013educag-1} 

}



\end{knitrout}
 \label{fig:edu.Asthma.2013}
\end{figure}

%latex.default(tabl.educag3, title = "Variables", file = "", append = TRUE,     rgroup = "Education group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by education levels,",         set_Years, sep = " "), label = paste("tab:edu", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence  among adults by education level, 2013\label{tab:edu.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Education group}&&&&&\tabularnewline
~~Some High School&10.2 (8.08-12.4)&81,969&1.00&0.00&1.00\tabularnewline
~~High School Graduate&10.1 (8.05-12.2)&74,096&1.03&0.20&0.88\tabularnewline
~~Some University&12.0 (10.0-14.0)&85,617&1.10&0.20&0.62\tabularnewline
~~University Graduate&8.35 (6.78-9.91)&47,740&0.80&0.23&0.35\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
 
 \newpage
\begin{itemize}

\item Figure \ref{fig:income.Asthma.2013} shows that adults whose annual household income is 
$<$15k, had a higher current asthma prevalence than those in other income groups.

\item Those in the \$50+k income range had a 22\% lower possibility of reporting asthma than those whose annual income was less than \$14,999. This difference was not significant (p-value $>$ 0.05).  For further information, refer to Table \ref{tab:income.Asthma.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Current asthma prevalence among adults by household income level, 
         2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013incomg-1} 

}



\end{knitrout}
 \label{fig:income.Asthma.2013}
\end{figure}

%latex.default(tabl.incomg, title = "Variables", file = "", append = TRUE,     rgroup = "Income group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by income levels,",         set_Years, sep = " "), label = paste("tab:income", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence  among adults by income levels, 2013\label{tab:income.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Income group}&&&&&\tabularnewline
~~\textless15k&11.4 (9.77-13.1)&138,607&1.00&0.00&1.00\tabularnewline
~~15k-\textless25k&10.2 (7.97-12.4)& 66,134&1.06&0.16&0.70\tabularnewline
~~25k-\textless35k&10.1 (7.00-13.2)& 20,369&1.16&0.21&0.47\tabularnewline
~~35k-\textless50k&7.75 (4.14-11.3)& 11,298&0.94&0.30&0.84\tabularnewline
~~50+k&5.95 (3.17-8.74)&  8,478&0.78&0.32&0.46\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

%%%%%%%%%%%%%%%%% Marial Status %%%%%%%%%%%%%%%%%%%%%%%%%
 \newpage
\begin{itemize}

\item Adults who reported being an Unmarried Couple at the time of the interview had the highest current asthma prevalence among all marital status groups. Refer to figure \ref{fig:marital.Asthma.2013}.

\item Those who were Unmarried Couples had a 30\% higher possibility of having asthma compared to those who reported being Married. This difference was not significant (p-value $>$ 0.05). Refer to Table \ref{tab:marital.Asthma.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Current asthma prevalence among adults by marital status,
         2013}
\label{fig:marital.Asthma.2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013marital2-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.marital, title = "Variables", file = "", append = TRUE,     rgroup = "Marital group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by marital status,",         set_Years, sep = " "), label = paste("tab:marital", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence  among adults by marital status, 2013\label{tab:marital.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Marital group}&&&&&\tabularnewline
~~Married&8.97 (7.61-10.3)&97,357&1.00&0.00&1.00\tabularnewline
~~Divorced&11.5 (8.68-14.3)&60,811&1.17&0.19&0.41\tabularnewline
~~Widowed&10.7 (7.93-13.5)&32,083&1.22&0.22&0.37\tabularnewline
~~Separated&11.8 (6.92-16.8)&28,468&1.30&0.27&0.33\tabularnewline
~~Never Married&9.96 (7.55-12.3)&49,009&1.12&0.21&0.57\tabularnewline
~~Unmarried Couple&12.4 (8.71-16.1)&20,483&1.30&0.24&0.26\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
%%%%%%%%%%%%%%%%%% employment status %%%%%%%%%%
 \newpage
\begin{itemize}


\item Adults who reported being unable to work at the time of the interview, had the highest current asthma prevalence (Figure \ref{fig:employ.Asthma.2013}).

\item Adults who were out of work, retired, and unable to work were 1.62, 1.78, and 2.66 times more likely, respectively, to report currently having asthma compared to those who reported being employed. These differences were significant (p-value $<$ 0.05). 
Data is shown in Table \ref{tab:employ.Asthma.2013}.

%\item Those who are rownames(t.asma.current.socio)[24], 
%rownames(t.asma.current.socio)[25], rownames(t.asma.current.socio)[26] or,
%rownames(t.asma.current.socio)[27] have the same set_Measure in statistical terms.

\end{itemize}

\begin{figure}[H]
\caption{Current asthma prevalence among adults by employment status, 
         2013}
\label{fig:employ.Asthma.2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013employ-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.emplrec2, title = "Variables", file = "",     append = TRUE, rgroup = "Employment status", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, " among adults by employment status,",         set_Years, sep = " "), label = paste("tab:employ", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence  among adults by employment status, 2013\label{tab:employ.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Employment status}&&&&&\tabularnewline
~~Employed&7.97 (6.45-9.50)&89,729&1.00&0.00&1.00\tabularnewline
~~Out of work&13.8 (9.17-18.4)&38,633&1.62&0.24&0.04\tabularnewline
~~Homework&10.2 (8.05-12.3)&52,914&0.83&0.20&0.38\tabularnewline
~~Student&10.8 (6.92-14.8)&19,157&0.70&0.35&0.31\tabularnewline
~~Retired&9.96 (8.08-11.8)&48,385&1.78&0.24&0.01\tabularnewline
~~Unable to work&17.8 (13.3-22.3)&40,022&2.66&0.24&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%%%%%%%%%%%%%%%% HRQOL %%%%%%%%%%%%%%%%%%%%%%%%%
 \newpage
\subsubsection{Health related quality of life}


 \begin{itemize}

\item Figure \ref{fig:fairpoor.Asthma.2013} shows that current asthma prevalence is 
\ifthenelse{
 705 < 
  1604}{higher}{lower} in persons who perceive their health as fair / poor than those who claim be excellent/very good.

\item Adults who perceived their health as fair or poor had a 3.15 times higher likelihood of reporting currently having asthma compared to those who perceived their health as very good. This difference was significant (p-value $<$ 0.05). Data is shown in Table \ref{tab:fairpoor.Asthma.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Current asthma prevalence among adults according to health perception,
         2013}
\label{fig:fairpoor.Asthma.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013poorh-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.fairpoor, title = "Variables", file = "",     append = TRUE, rgroup = "Health Perception", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, " among adults according to health perception,",         set_Years, sep = " "), label = paste("tab:fairpoor",         set_DiseaseF, set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence  among adults according to health perception, 2013\label{tab:fairpoor.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Health Perception}&&&&&\tabularnewline
~~Very Good&7.05 (5.96-8.15)&128,172&1.00&0.00&1.00\tabularnewline
~~Fair / Poor&16.0 (14.0-18.0)&159,663&3.15&0.21&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
\newpage

%%%%%%%%%%%%% physical unhealthy %%%%%%%%%%%%
 \newpage
\begin{itemize}

\item Adults who reported being physically unhealthy for 14 days or more in the past 30 days had a  
\ifthenelse{
 871 >
  1919}{lower}{higher} current asthma prevalence compared to those who reported being physically unhealthy for less than 13 days in the last 30 days.

%\item Table \ref{tab:phys} shows the estimations of the set_Measure.

\item Adults who felt physically impaired for 14 or more days had a 2.46 higher likelihood of reporting having asthma at the time of the interview compared to those who felt physically impaired for 13 days or less. This difference was significant (p-value $<$ 0.05). (See Table \ref{tab:phys.Asthma.2013}).

\end{itemize}

\begin{figure}[H]
\caption{Current asthma prevalence among adults according to physical health perception, 2013}
\label{fig:phys.Asthma.2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013physchlcat-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.physhlcat, title = "Variables", file = "",     append = TRUE, rgroup = "Days with physical symptoms", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, "among adults by days with physical symptoms,",         set_Years, sep = " "), label = paste("tab:phys", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence among adults by days with physical symptoms, 2013\label{tab:phys.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Days with physical symptoms}&&&&&\tabularnewline
~~0-13 days&8.71 (7.66-9.76)&208,750&1.00&0.00&1.00\tabularnewline
~~14 or more days&19.1 (15.8-22.5)& 78,640&2.46&0.21&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%%%%%%%%%%%%%%%%%%%%%%%% Mentally unhelathy %%%%%%%%%%%%%%
 \newpage
\begin{itemize}

\item Current asthma prevalence among adults who reported feeling mentally unhealthy for 14 days or more in the last month was \ifthenelse{901 > 
  1795}{lower}{higher} than those who reported feeling mentally unhealthy for less than 14 days (Figure \ref{fig:mental.Asthma.2013}).

%\item set_Measure for this groups are presented in the Table \ref{tab:mental}.

\item  Adults who felt mentally unhealthy for 14 or more days had a 43\% higher possibility of currently having asthma compared to those who reported 0-13 days. This difference was marginally significant (p-value $>$ 0.05). (See Table \ref{tab:mental.Asthma.2013}).

\end{itemize}

\begin{figure}[H]
\centering
\caption{Current asthma prevalence among adults by days of frequent mental distress, 2013}
\label{fig:mental.Asthma.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013mentdist-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.mentdist, title = "Variables", file = "",     append = TRUE, rgroup = "Mentally Unhealthy", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, "among",         set_Population, "by days of frequent mental distress,",         set_Years, sep = " "), label = paste("tab:mental", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence among adults by days of frequent mental distress, 2013\label{tab:mental.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Mentally Unhealthy}&&&&&\tabularnewline
~~0-13 days&9.01 (7.96-10.0)&216,764&1.00&0.00&1.00\tabularnewline
~~14 or more days&17.9 (14.4-21.4)& 69,823&1.43&0.21&0.09\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}



%%%%%%%%%%%%%%%%%%% poorhlcat %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 \newpage
\begin{itemize}

\item A \ifthenelse{
 1384 > 
  2139}{lower}{higher} 
current asthma prevalence was observed among adults who were unable to perform their usual activities for 14 or more days due to physical or mental impairment, compared to those reporting less than 14 days. Refer to Figure \ref{fig:poor.Asthma.2013}.



\item Persons who could not conduct their usual daily activities for more than 14 days in the last month were 56\% more likely to report asthma compared to those who felt this way for at most 13 days in the last 30 month.

\end{itemize}

\begin{figure}[H]
\caption{Current asthma prevalence among adults who were unable to conduct usual activities due to physical or mental impediment, 2013}
\label{fig:poor.Asthma.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013poor-1} 

}



\end{knitrout}
\end{figure}

%latex.default(tabl.poorhlcat, title = "Variables", file = "",     append = TRUE, rgroup = "Activiy limitation", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, "among",         set_Population, "who were unable to cunduct usual activities due to physical or mental impairment,",         set_Years, sep = " "), label = paste("tab:poor", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence among adults who were unable to conduct usual activities due to physical or mental impairment, 2013\label{tab:poor.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Activity limitation}&&&&&\tabularnewline
~~0-13 days&13.8 (11.8-15.8)&137,176&1.00&0.00&1.00\tabularnewline
~~14 or more days&21.3 (17.0-25.7)& 52,913&1.56&0.25&0.07\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%%%%%%%%%%%%%%%%%%%%% unhlthy %%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\begin{itemize}

\item As seen in Figure \ref{fig:unhlthy.Asthma.2013}, those adults who felt mentally or physically unhealthy for more than 14 days in the last 30 days had a \ifthenelse{
8>
17}{lower}{higher} 
current asthma prevalence than those reporting less than 14 days.

%\item The prevalence for those who felt mentally or fisically unhealthy is more than twice of the
%prevalence of those who felt healthy for at least 14 days in the past 30(Table \ref{tab:unhlthy}).

\item Those persons who felt mentally or physically unhealthy for more than 14 days in the last month were 92\% more likely to report having asthma compared to those who felt mentally or physically unhealthy for at most 13 days in the last 30 days. Data shown in Table \ref{tab:unhlthy.Asthma.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Current asthma prevalence among adults by unhealthy days, 2013}
\label{fig:unhlthy.Asthma.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Asthma/Current/Adult/2013unhealthy-1} 

}



\end{knitrout}
\end{figure}

%latex.default(tabl.unhlthy, title = "Variables", file = "", append = TRUE,     rgroup = "Unhealthy Days", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, "among", set_Population,         "by unhealthy days,", set_Years, sep = " "), label = paste("tab:unhlthy",         set_DiseaseF, set_Years, sep = "."))%
\begin{table}[H]
\caption{Current asthma prevalence among adults by unhealthy days, 2013\label{tab:unhlthy.Asthma.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Unhealthy Days}&&&&&\tabularnewline
~~0-13 days&8.18 (7.11-9.25)&176,324&1.00&0.00&1.00\tabularnewline
~~14 or more days&17.1 (14.5-19.7)&113,593&1.92&0.19&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


 \subsubsection{Interpretation}

An estimated 289,917 (10.29\%) adults in Puerto Rico had asthma in the 2013 period. When the prevalence of asthma was evaluated by socio-demographic factors, including age, educational level, and marital status, no specific group was observed to be disproportionately affected. With regard to gender asthma was found to be 2.22 times higher in women. Although not statistically significant, those in the $35k-50k income range and those in the range of more than $50k annually had 29 and 39 times, respectively, lower probability of reporting currently having asthma than those in the group who reported a household income of less than $15k annually.

With regard to the health related quality of life measures, the likelihood of reporting currently having asthma in adults who perceived their health as fair or poor was 3.15 times higher than those who considered their health to be good, very good or excellent. Adults who said that they felt physically unwell for 14 days or more of the last 30 days were 2.46 times more likely to report current asthma prevalence than those reporting less than 13 days. In the same manner, adults who felt mentally distressed for 14 days or more in a month were 1.43 times more likely to report currently having asthma than those feeling mentally distressed for less than 13 days. Of 1.6 million adults who were unable to carry out their normal activities for more than 14 days in a month, 17.1 (14.5-19.7) percent reported currently having asthma.

%Summary tables
\newpage
\subsubsection{Summary tables}

In this section we provide a set of summary tables of asthma among Puerto Rican adults during the year 2013. The tables aggregate all the analysis conducted in this report for easy reference, or to be used as an annex for the preparation of other documents such as funding applications. For the interpretation of each result, please refer to the corresponding section of the document.

% Overall
\begin{table}[H]
\caption{Current asthma prevalence among adults in Puerto Rico, 2013\label{tab:Overall.tabl.Asthma.2013.B}} 
\begin{center}
\begin{tabular}{llll}
\hline\hline
\multicolumn{1}{l}{Group}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases}&\multicolumn{1}{c}{Sample Size}\tabularnewline
\hline
Adults&10.29 (9.27-11.32)&289,917&6,011\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}
 
%latex.default(object = SocioD.tabl, title = "Variables", file = "",     append = TRUE, rgroup = c("Age group", "Gender", "Escolarity",         "Household income", "Marital status", "Employment status"),     n.rgroup = c(6, 2, 4, 5, 6, 6), table.env = T, longtable = F,     here = T, caption = paste(set_Measure, " among adults by socio-demographic variables,",         set_Years, sep = " "), label = "tab:SocioD.tabl")%
\begin{table}[H]
\caption{Current asthma prevalence  among adults by socio-demographic variables, 2013\label{tab:SocioD.tabl}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Number}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Age group}&&&&&\tabularnewline
~~18-24&13.3 (9.78-16.9)&50,633&1.00&0.00&1.00\tabularnewline
~~25-34&8.60 (5.62-11.5)&42,042&0.50&0.32&0.03\tabularnewline
~~35-44&9.81 (7.40-12.2)&47,193&0.43&0.32&0.01\tabularnewline
~~45-54&9.71 (7.50-11.9)&47,072&0.45&0.33&0.01\tabularnewline
~~55-64&12.4 (9.93-14.9)&54,507&0.48&0.35&0.04\tabularnewline
~~65+&8.85 (7.39-10.3)&48,469&0.28&0.39&0.00\tabularnewline
\hline
{\bfseries Gender}&&&&&\tabularnewline
~~Males&7.01 (5.54-8.47)& 92,596&1.00&0.00&1.00\tabularnewline
~~Females&13.1 (11.7-14.6)&197,321&2.22&0.15&0.00\tabularnewline
\hline
{\bfseries Escolarity}&&&&&\tabularnewline
~~Some High School&10.2 (8.08-12.4)&81,969&1.00&0.00&1.00\tabularnewline
~~High School Graduate&10.1 (8.05-12.2)&74,096&1.03&0.20&0.88\tabularnewline
~~Some University&12.0 (10.0-14.0)&85,617&1.10&0.20&0.62\tabularnewline
~~University Graduate&8.35 (6.78-9.91)&47,740&0.80&0.23&0.35\tabularnewline
\hline
{\bfseries Household income}&&&&&\tabularnewline
~~\textless15k&11.4 (9.77-13.1)&138,607&1.00&0.00&1.00\tabularnewline
~~15k-\textless25k&10.2 (7.97-12.4)& 66,134&1.06&0.16&0.70\tabularnewline
~~25k-\textless35k&10.1 (7.00-13.2)& 20,369&1.16&0.21&0.47\tabularnewline
~~35k-\textless50k&7.75 (4.14-11.3)& 11,298&0.94&0.30&0.84\tabularnewline
~~50+k&5.95 (3.17-8.74)&  8,478&0.78&0.32&0.46\tabularnewline
\hline
{\bfseries Marital status}&&&&&\tabularnewline
~~Married&8.97 (7.61-10.3)&97,357&1.00&0.00&1.00\tabularnewline
~~Divorced&11.5 (8.68-14.3)&60,811&1.17&0.19&0.41\tabularnewline
~~Widowed&10.7 (7.93-13.5)&32,083&1.22&0.22&0.37\tabularnewline
~~Separated&11.8 (6.92-16.8)&28,468&1.30&0.27&0.33\tabularnewline
~~Never Married&9.96 (7.55-12.3)&49,009&1.12&0.21&0.57\tabularnewline
~~Unmarried Couple&12.4 (8.71-16.1)&20,483&1.30&0.24&0.26\tabularnewline
\hline
{\bfseries Employment status}&&&&&\tabularnewline
~~Employed&7.97 (6.45-9.50)&89,729&1.00&0.00&1.00\tabularnewline
~~Out of work&13.8 (9.17-18.4)&38,633&1.62&0.24&0.04\tabularnewline
~~Homework&10.2 (8.05-12.3)&52,914&0.83&0.20&0.38\tabularnewline
~~Student&10.8 (6.92-14.8)&19,157&0.70&0.35&0.31\tabularnewline
~~Retired&9.96 (8.08-11.8)&48,385&1.78&0.24&0.01\tabularnewline
~~Unable to work&17.8 (13.3-22.3)&40,022&2.66&0.24&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 

 
%latex.default(object = hrqol.tabl, title = "Variables", file = "",     append = TRUE, rgroup = c("Health perception", "Physical unhealthy",         "Mental unhealthy", "Activity limitation", "Physical and mental unhealthy"),     n.rgroup = c(2, 2, 2, 2, 2), rowname = c("Very Good", "Fair / Poor",         rep(c("0-13 days", "14 or more days"), 4)), table.env = T,     here = T, caption = paste(set_Measure, " among adults by health related quality of life variables,",         set_Years, sep = " "), label = "tab:hrqol.tabl")%
\begin{table}[H]
\caption{Current asthma prevalence  among adults by health related quality of life variables, 2013\label{tab:hrqol.tabl}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Number}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Health perception}&&&&&\tabularnewline
~~Very Good&7.05 (5.96-8.15)&128,172&1.00&0.00&1.00\tabularnewline
~~Fair / Poor&16.0 (14.0-18.0)&159,663&3.15&0.21&0.00\tabularnewline
\hline
{\bfseries Physical unhealthy}&&&&&\tabularnewline
~~0-13 days&8.71 (7.66-9.76)&208,750&1.00&0.00&1.00\tabularnewline
~~14 or more days&19.1 (15.8-22.5)& 78,640&2.46&0.21&0.00\tabularnewline
\hline
{\bfseries Mental unhealthy}&&&&&\tabularnewline
~~0-13 days&9.01 (7.96-10.0)&216,764&1.00&0.00&1.00\tabularnewline
~~14 or more days&17.9 (14.4-21.4)& 69,823&1.43&0.21&0.09\tabularnewline
\hline
{\bfseries Activity limitation}&&&&&\tabularnewline
~~0-13 days&13.8 (11.8-15.8)&137,176&1.00&0.00&1.00\tabularnewline
~~14 or more days&21.3 (17.0-25.7)& 52,913&1.56&0.25&0.07\tabularnewline
\hline
{\bfseries Physical and mental unhealthy}&&&&&\tabularnewline
~~0-13 days&8.18 (7.11-9.25)&176,324&1.00&0.00&1.00\tabularnewline
~~14 or more days&17.1 (14.5-19.7)&113,593&1.92&0.19&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

