
%----------------------------------------------------------------------------------------
%            RESULTS
%----------------------------------------------------------------------------------------
\subsubsection{Overall}

%----------------------------FIRST FIGURE------------------------------------------------



%latex.default(object = Overall.tabl[, c(-1, -2)], title = "Group",     file = "", rowname = c("Adults"), colhead = c("Prevalence",         "Cases", "Sample Size"), append = TRUE, table.env = T,     here = T, caption = paste(set_Measure, " among adults in ",         set_Country, ", ", set_Years, sep = ""), label = paste("tab:Overall.tabl",         set_DiseaseF, set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence among adults in Puerto Rico, 2013\label{tab:Overall.tabl.Stroke.2013}} 
\begin{center}
\begin{tabular}{llll}
\hline\hline
\multicolumn{1}{l}{Group}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases}&\multicolumn{1}{c}{Sample Size}\tabularnewline
\hline
Adults&1.95 (1.57-2.32)&54,904&6,011\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}



%----------------------------------------------------------------------------------------

\begin{itemize}


\item The Stroke prevalence for the year 2013 among adults in Puerto Rico was 1.95 (1.57-2.32) percent, 
Table \ref{tab:Overall.tabl.Stroke.2013}.

\end{itemize}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%                     Definition of matrices for the tables                  %%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\newpage
\subsubsection{Socio-demographics}

\begin{itemize}

\item Figure \ref{fig:age.Stroke.2013} shows that the stroke prevalence for the age group of
65+
was higher when compared with the other groups.

\item Adults in the age group of 55-64, and 65+ had 6.03 times more possibility, and 7.7 times more possibility, respectively, of reporting stroke prevalence when compared with the 24-35 group. This differences were significant (p-value $<$ 0.05). See Table \ref{tab:age.reduced}. The 18-24 age group was excluded from the regression analysis because it does not had cases. The oringal six group information is at table \ref{tab:age.Stroke.2013}.


\end{itemize}


\begin{figure}[H]
\caption{Stroke prevalence among adults by age group, 
2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013ageg2-1} 

}



\end{knitrout}
\label{fig:age.Stroke.2013}
\end{figure}

% New tex table for age eliminating 18-24 age group

%\%latex.default(tabl.ageg2, title = ``Variables'', file = ``'', append =
%TRUE, rgroup = ``Age group'', colhead = c(``Prevalence'', ``Cases (N)'',
%``OR'', ``OR(SE)'', ``p-value''), longtable = F, table.env = T, here =
%T, caption = ``Stroke prevalence among adults by age group, 2013'',
%label = ``tab:age.reduced'')\%

\begin{table}[H]
\caption{Stroke prevalence among adults by age group, 2013\label{tab:age.reduced}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Age group}&&&&&\tabularnewline
~~25-34&0.38&  187,022&1.00&0.00&1.00\tabularnewline
~~35-44&1.2&  579,968&2.99&0.83&0.19\tabularnewline
~~45-54&1.31&  631,695&2.17&0.83&0.35\tabularnewline
~~55-64&3.96&1,733,798&6.03&0.85&0.03\tabularnewline
~~65+&4.32&2,357,941&7.7&0.90&0.02\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}
%latex.default(tabl.ageg2, title = "Variables", file = "", append = TRUE,     rgroup = "Age group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by age group,",         set_Years, sep = " "), label = paste("tab:age", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence  among adults by age group, 2013\label{tab:age.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Age group}&&&&&\tabularnewline
~~18-24&0 (0-0)&     0&1.00&0.00&1.00\tabularnewline
~~25-34&0.38 (0.00-0.99)& 1,870&1196&0.89&0.00\tabularnewline
~~35-44&1.20 (0.32-2.08)& 5,800&3571&0.42&0.00\tabularnewline
~~45-54&1.30 (0.59-2.01)& 6,317&2596&0.37&0.00\tabularnewline
~~55-64&3.96 (2.58-5.33)&17,338&7207&0.32&0\tabularnewline
~~65+&4.31 (3.24-5.38)&23,579&9205&0.37&0\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}



% SEX
\newpage
\begin{itemize}

\item Figure \ref{fig:sex.Stroke.2013} shows that males had a \ifthenelse{
210 < 180}{lower}{higher}
stroke prevalence when compared with females.

%\item Table \ref{tab:sex} shows the estimates for persons living with set_Disease in 
%set_Country with it 95\% confidence interval.

\item Among adults, females had 15\% less possibility of reporting stroke when compared with males. This difference was not significant (p-value $>$ 0.05). See Table \ref{tab:sex.Stroke.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Stroke prevalence among adults by sex group, 
2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013sex-1} 

}



\end{knitrout}
\label{fig:sex.Stroke.2013}
\end{figure}

%latex.default(tabl.sex, title = "Variables", file = "", append = TRUE,     rgroup = "Sex group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by sex group,",         set_Years, sep = " "), label = paste("tab:sex", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence  among adults by sex group, 2013\label{tab:sex.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Sex group}&&&&&\tabularnewline
~~Males&2.10 (1.46-2.75)&27,827&1.00&0.00&1.00\tabularnewline
~~Females&1.80 (1.39-2.22)&27,077&0.85&0.24&0.53\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%###################### educag ####################
\newpage
\begin{itemize}

\item When comparing by education level, those with
some high school
have the highest stroke prevalence. A 2\% of the stroke prevalence patients had some high school.
(Figure \ref{fig:edu.Stroke.2013}).

\item 
When observing the adjusted odds ratio the group some university had 11\% less possibility of reporting stroke prevalence than the comparison group (Some High School).
This difference was not significant (p-value $>$ 0.05).  Data shown in Table \ref{tab:edu.Stroke.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Stroke prevalence among adults by education levels, 
         2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013educag-1} 

}



\end{knitrout}
 \label{fig:edu.Stroke.2013}
\end{figure}

%latex.default(tabl.educag3, title = "Variables", file = "", append = TRUE,     rgroup = "Education group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by education levels,",         set_Years, sep = " "), label = paste("tab:edu", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence  among adults by education levels, 2013\label{tab:edu.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Education group}&&&&&\tabularnewline
~~Some High School&2.77 (1.86-3.68)&22,099&1.00&0.00&1.00\tabularnewline
~~High School Graduate&2.06 (1.31-2.81)&15,082&1.07&0.29&0.82\tabularnewline
~~Some University&1.35 (0.73-1.96)& 9,618&0.89&0.36&0.76\tabularnewline
~~University Graduate&1.41 (0.88-1.95)& 8,105&0.98&0.38&0.96\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
 
 \newpage
\begin{itemize}

\item Figure \ref{fig:income.Stroke.2013} shows that adults whose annual household income is 
$<$15k, have a stroke prevalence higher than the other income groups.

\item Those in the range of 35k-$<$50k had 53\% less possibility of reporting stroke than those whose annual income is less than \$ 14,999. This difference was not significant (p-value $>$ 0.05).  For further information, refer to Table \ref{tab:income.Stroke.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Stroke prevalence among adults by household income levels, 
         2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013incomg-1} 

}



\end{knitrout}
 \label{fig:income.Stroke.2013}
\end{figure}

%latex.default(tabl.incomg, title = "Variables", file = "", append = TRUE,     rgroup = "Income group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by income levels,",         set_Years, sep = " "), label = paste("tab:income", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence  among adults by income levels, 2013\label{tab:income.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Income group}&&&&&\tabularnewline
~~\textless15k&2.65 (1.97-3.33)&31,997&1.00&0.00&1.00\tabularnewline
~~15k-\textless25k&1.52 (0.75-2.28)& 9,840&0.74&0.33&0.37\tabularnewline
~~25k-\textless35k&2.41 (0.84-3.97)& 4,850&1.39&0.45&0.46\tabularnewline
~~35k-\textless50k&0.69 (0.06-1.32)& 1,011&0.47&0.56&0.18\tabularnewline
~~50+k&1.22 (0.09-2.34)& 1,738&0.89&0.61&0.85\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

%%%%%%%%%%%%%%%%% Marial Status %%%%%%%%%%%%%%%%%%%%%%%%%
 \newpage
\begin{itemize}

\item Adults who were 
widowed at the time of the interview, had the highest stroke prevalence among marital status. Refer to figure \ref{fig:marital.Stroke.2013}.

\item Those who were separated had 77\% less possibility of having stroke prevalence when compared with those who responded being married. This difference was significant (p-value $<$ 0.05). Refere to Table \ref{tab:marital.Stroke.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Stroke prevalence among adults by marital status,
         2013}
\label{fig:marital.Stroke.2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013marital2-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.marital, title = "Variables", file = "", append = TRUE,     rgroup = "Marital group", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, " among adults by marital status,",         set_Years, sep = " "), label = paste("tab:marital", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence  among adults by marital status, 2013\label{tab:marital.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Marital group}&&&&&\tabularnewline
~~Married&2.27 (1.65-2.90)&24,734&1.00&0.00&1.00\tabularnewline
~~Divorced&2.62 (1.49-3.75)&13,835&1.28&0.30&0.40\tabularnewline
~~Widowed&3.51 (2.12-4.90)&10,473&0.92&0.30&0.81\tabularnewline
~~Separated&0.43 (0.00-0.88)& 1,030&0.23&0.59&0.01\tabularnewline
~~Never Married&0.82 (0.16-1.48)& 4,031&1.72&0.43&0.20\tabularnewline
~~Unmarried Couple&0.48 (-0.0-1.02)&   800&0.47&0.63&0.24\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
%%%%%%%%%%%%%%%%%% employment status %%%%%%%%%%
 \newpage
\begin{itemize}


\item Those adults who were 
unable to work at the moment of the interview, had the highest stroke prevalence (Figure \ref{fig:employ.Stroke.2013}).

\item Adults who were student, unable to work had 0 times more possibility, 5.5 times more possibility, respectively, of reporting stroke prevalence when compared with those who responded being employed. This differences were significant (p-value $<$ 0.05). 
Data shown in Table \ref{tab:employ.Stroke.2013}.

%\item Those who are rownames(t.asma.current.socio)[24], 
%rownames(t.asma.current.socio)[25], rownames(t.asma.current.socio)[26] or,
%rownames(t.asma.current.socio)[27] have the same set_Measure in statistical terms.

\end{itemize}

\begin{figure}[H]
\caption{Stroke prevalence among adults by employment status, 
         2013}
\label{fig:employ.Stroke.2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013employ-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.emplrec2, title = "Variables", file = "",     append = TRUE, rgroup = "Employment status", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, " among adults by employment status,",         set_Years, sep = " "), label = paste("tab:employ", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence  among adults by employment status, 2013\label{tab:employ.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Employment status}&&&&&\tabularnewline
~~Employed&0.80 (0.38-1.22)& 9,054&1.00&0.00&1.00\tabularnewline
~~Out of work&0.91 (0.03-1.79)& 2,549&1.13&0.62&0.84\tabularnewline
~~Homework&1.55 (0.94-2.16)& 8,066&1.23&0.44&0.63\tabularnewline
~~Student&0 (0-0)&     0&0.00&0.62&0.00\tabularnewline
~~Retired&3.60 (2.49-4.71)&17,473&1.36&0.43&0.47\tabularnewline
~~Unable to work&7.91 (5.06-10.7)&17,763&5.50&0.44&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%%%%%%%%%%%%%%%% HRQOL %%%%%%%%%%%%%%%%%%%%%%%%%
 \newpage
\subsubsection{Health related quality of life}


 \begin{itemize}

\item Figure \ref{fig:fairpoor.Stroke.2013} shows that stroke prevalence  was 
\ifthenelse{
 83 < 
  399}{higher}{lower} in persons who perceive their health has fair / poor,
than those who claim to have a very good health.

\item Adults who perceive their health as fair or poor had 5\% less possibility of reporting stroke prevalence when compared with those who perceived their health as very good. This difference was not significant (p-value $>$ 0.05). Data shown in Table \ref{tab:fairpoor.Stroke.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Stroke prevalence among adults according to health perception,
         2013}
\label{fig:fairpoor.Stroke.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013poorh-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.fairpoor, title = "Variables", file = "",     append = TRUE, rgroup = "Health Perception", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, " among adults according to health perception,",         set_Years, sep = " "), label = paste("tab:fairpoor",         set_DiseaseF, set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence  among adults according to health perception, 2013\label{tab:fairpoor.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Health Perception}&&&&&\tabularnewline
~~Very Good&0.83 (0.53-1.14)&15,240&1.00&0.00&1.00\tabularnewline
~~Fair / Poor&3.99 (3.09-4.89)&39,665&0.95&0.32&0.88\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 
\newpage

%%%%%%%%%%%%% physical unhealthy %%%%%%%%%%%%
 \newpage
\begin{itemize}

\item Adults who reported being physically unhealthy for 14 days or more in the past 30 days, had an  
\ifthenelse{
 152 >
  432}{lower}{higher} stroke prevalence when compared with 
those who reported being physically unhealthy for less than 13 days in the last 30 days.

%\item Table \ref{tab:phys} shows the estimations of the set_Measure.

\item Adults who felt physically impaired for 14 days or more had 4\% less possibility of reporting having stroke at the moment of the interview, when compared with those who felt physically impaired for 13 days or less (See Table \ref{tab:phys.Stroke.2013}).

\end{itemize}

\begin{figure}[H]
\caption{Stroke prevalence among adults according to physical health perception, 2013}
\label{fig:phys.Stroke.2013}
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013physchlcat-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.physhlcat, title = "Variables", file = "",     append = TRUE, rgroup = "Days with physical symptoms", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, "among adults by days with physical symptoms,",         set_Years, sep = " "), label = paste("tab:phys", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence among adults by days with physical symptoms, 2013\label{tab:phys.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Days with physical symptoms}&&&&&\tabularnewline
~~0-13 days&1.52 (1.15-1.88)&36,499&1.00&0.00&1.00\tabularnewline
~~14 or more days&4.32 (2.92-5.72)&17,680&0.96&0.38&0.92\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%%%%%%%%%%%%%%%%%%%%%%%% Mentally unhelathy %%%%%%%%%%%%%%
 \newpage
\begin{itemize}

\item Stroke prevalence among adults who reported feeling mentally unhealthy for more than 13 days in the last month was \ifthenelse{177 > 
  288}{lower}{higher} when compared with their counterpart (Figure \ref{fig:mental.Stroke.2013}).

%\item set_Measure for this groups are presented in the Table \ref{tab:mental}.

\item  Adults who felt mentally impaired for 14 or more days had 43\% less possibility of having stroke prevalence when compared with those who answered 0-13 days. This difference was not significant (p-value $>$ 0.05). (See Table \ref{tab:mental.Stroke.2013}).

\end{itemize}

\begin{figure}[H]
\centering
\caption{Stroke prevalence among adults by days of frequent mental distress, 2013}
\label{fig:mental.Stroke.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013mentdist-1} 

}



\end{knitrout}
 \end{figure}

%latex.default(tabl.mentdist, title = "Variables", file = "",     append = TRUE, rgroup = "Mentally Unhealthy", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, "among",         set_Population, "by days of frequent mental distress,",         set_Years, sep = " "), label = paste("tab:mental", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence among adults by days of frequent mental distress, 2013\label{tab:mental.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Mentally Unhealthy}&&&&&\tabularnewline
~~0-13 days&1.77 (1.39-2.14)&42,584&1.00&0.00&1.00\tabularnewline
~~14 or more days&2.88 (1.57-4.19)&11,224&0.57&0.42&0.19\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}



%%%%%%%%%%%%%%%%%%% poorhlcat %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 \newpage
\begin{itemize}

\item A \ifthenelse{
 227 > 
  397}{lower}{higher} 
stroke prevalence was observed among adults who were unable to perform their usual activities for 14 days or more due to physical or mental impairment, when compared with the other group. Refer to Figure \ref{fig:poor.Stroke.2013}.



\item Persons who could not conduct their usual daily activities for more than 14 days in the last month had 55\% less possibility of reporting stroke when compared with those who felt this way for at most 13 days in the last 30.

\end{itemize}

\begin{figure}[H]
\caption{Stroke prevalence among adults who were unable to conduct usual activities due to physical or mental impediment, 2013}
\label{fig:poor.Stroke.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013poor-1} 

}



\end{knitrout}
\end{figure}

%latex.default(tabl.poorhlcat, title = "Variables", file = "",     append = TRUE, rgroup = "Activiy limitation", colhead = c("Prevalence",         "Cases (N)", "OR", "OR(SE)", "p-value"), longtable = F,     table.env = T, here = T, caption = paste(set_Measure, "among",         set_Population, "who were unable to cunduct usual activities due to physical or mental impairment,",         set_Years, sep = " "), label = paste("tab:poor", set_DiseaseF,         set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence among adults who were unable to cunduct usual activities due to physical or mental impairment, 2013\label{tab:poor.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Activiy limitation}&&&&&\tabularnewline
~~0-13 days&2.27 (1.58-2.95)&22,502&1.00&0.00&1.00\tabularnewline
~~14 or more days&3.97 (2.23-5.72)& 9,819&0.45&0.51&0.13\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


%%%%%%%%%%%%%%%%%%%%% unhlthy %%%%%%%%%%%%%%%%%%%%%%%%%%
\newpage
\begin{itemize}

\item As seen in Figure \ref{fig:unhlthy.Stroke.2013}, those adults who felt mentally or physically unhealthy for more than 14 days in the last 30 days, had \ifthenelse{
1>
3}{lower}{higher} 
stroke prevalence when compared with their counterpart.

%\item The prevalence for those who felt mentally or fisically unhealthy is more than twice of the
%prevalence of those who felt healthy for at least 14 days in the past 30(Table \ref{tab:unhlthy}).

\item Those persons who felt mentally or physically unhealthy for more than 14 days in the last month had 15\% less possibility of reporting stroke when compared with those who felt mentally or physically unhealthy for at most 13 days in the last 30 days. Data shown in Table \ref{tab:unhlthy.Stroke.2013}.

\end{itemize}

\begin{figure}[H]
\caption{Stroke prevalence among adults by unhealthy days, 2013}
\label{fig:unhlthy.Stroke.2013}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}

{\centering \includegraphics[width=\maxwidth]{/media/truecrypt2/ORP2/BRFSS/Objects/Country/Puerto_Rico/Disease/Stroke/Prevalence/Adult/2013unhealthy-1} 

}



\end{knitrout}
\end{figure}

%latex.default(tabl.unhlthy, title = "Variables", file = "", append = TRUE,     rgroup = "Unhealthy Days", colhead = c("Prevalence", "Cases (N)",         "OR", "OR(SE)", "p-value"), longtable = F, table.env = T,     here = T, caption = paste(set_Measure, "among", set_Population,         "by unhealthy days,", set_Years, sep = " "), label = paste("tab:unhlthy",         set_DiseaseF, set_Years, sep = "."))%
\begin{table}[H]
\caption{Stroke prevalence among adults by unhealthy days, 2013\label{tab:unhlthy.Stroke.2013}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Cases (N)}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Unhealthy Days}&&&&&\tabularnewline
~~0-13 days&1.51 (1.13-1.88)&32,532&1.00&0.00&1.00\tabularnewline
~~14 or more days&3.37 (2.34-4.40)&22,372&0.85&0.30&0.60\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


 \subsubsection{Remarks}

An estimate of 54,904 
(1.95\%) adult in Puerto Rico had stroke as of the period of 2013.
When evaluating by the socio-demographic variables, no specific group has been disproportionately affected with stroke in age groups, educational level or marital status. With regards to gender the stroke was 0.85 times higher in women. Although not statistically significant those in the household income range of 35k-50k and those in the range of more than 50k annually, had 0 and \ensuremath{-2} respectively less possibility of stroke prevalence that those  in group of those who receive less than 15k annually.

Moving to the health related quality of life measures, the possibility of reporting stroke prevalence in adults that perceived their health as fair or poor was 0.95 times higher than those who considered their health as good, very good or excellent. The adults who said that they felt physically bad for 14 days or more for the last 30 days had 0.96 times higher possibility of reporting stroke prevalence than those less than 13 days. In the same manner, adults who felt mentally distressed for 14 days or more in a month had 0.57 times higher possibility of reporting stroke prevalence than those less than 13 days feeling mentally distressed. From 1.6 million adults who were unable to carry on with their normal activities more than 14 days in a month, 3.37 (2.34-4.40) percent reported stroke prevalence. 

People who exercise, or are exposed to physical activities reported \ensuremath{-1} \% higher risk of stroke than those who don't.  Regarding body mass index (BMI), those obese and overweight had 0\% and 1\% respectively more possibility of stroke prevalence than those neither obese nor overweight. The estimation of the stroke prevalence on smokers was 1.94 (1.55-2.34) percent.  Adults with diabetes were \ensuremath{-1}\5 less likely to have stroke prevalence than their counterpart.


%\newpage
%\vspace{1cm}

Progress has been made in understanding the burden of stroke in Puerto Rico. Advancements in the diagnose and treatment of the condition have had considerably improved in the last 20 years, but it is still an uncontrolled condition. The disclosed information is part of the effort of the Puerto Rico stroke Project to provide an update of the state of stroke in our country. The report presents information that can aid in the development of public policy, guide changes in the health care system, monitor population stroke control, enhance educational materials, and guide all efforts to target factors of disparities as a way of reducing the morbidity and mortality associated with stroke in Puerto Rico.

%Summary tables
\newpage
\subsubsection{Summary tables}
In this section we provide a set of summary tables of stroke among adults Puerto Rico for the years 2013. The tables aggregate all the analysis conducted in this report for an easy to print and carry document for reference, or to be used as an annex for the preparation of other documents such as an application for funds. For the interpretation of each result, please refer to the corresponding section in the document.


 
%latex.default(object = SocioD.tabl, title = "Variables", file = "",     append = TRUE, rgroup = c("Age group", "Gender", "Escolarity",         "Household income", "Marital status", "Employment status"),     n.rgroup = c(6, 2, 4, 5, 6, 6), table.env = T, longtable = F,     here = T, caption = paste(set_Measure, " among adults by socio-demographic variables,",         set_Years, sep = " "), label = "tab:SocioD.tabl")%
\begin{table}[H]
\caption{Stroke prevalence  among adults by socio-demographic variables, 2013\label{tab:SocioD.tabl}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Number}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Age group}&&&&&\tabularnewline
~~18-24&0 (0-0)&     0&1.00&0.00&1.00\tabularnewline
~~25-34&0.38 (0.00-0.99)& 1,870&1196&0.89&0.00\tabularnewline
~~35-44&1.20 (0.32-2.08)& 5,800&3571&0.42&0.00\tabularnewline
~~45-54&1.30 (0.59-2.01)& 6,317&2596&0.37&0.00\tabularnewline
~~55-64&3.96 (2.58-5.33)&17,338&7207&0.32&0\tabularnewline
~~65+&4.31 (3.24-5.38)&23,579&9205&0.37&0\tabularnewline
\hline
{\bfseries Gender}&&&&&\tabularnewline
~~Males&2.10 (1.46-2.75)&27,827&1.00&0.00&1.00\tabularnewline
~~Females&1.80 (1.39-2.22)&27,077&0.85&0.24&0.53\tabularnewline
\hline
{\bfseries Escolarity}&&&&&\tabularnewline
~~Some High School&2.77 (1.86-3.68)&22,099&1.00&0.00&1.00\tabularnewline
~~High School Graduate&2.06 (1.31-2.81)&15,082&1.07&0.29&0.82\tabularnewline
~~Some University&1.35 (0.73-1.96)& 9,618&0.89&0.36&0.76\tabularnewline
~~University Graduate&1.41 (0.88-1.95)& 8,105&0.98&0.38&0.96\tabularnewline
\hline
{\bfseries Household income}&&&&&\tabularnewline
~~\textless15k&2.65 (1.97-3.33)&31,997&1.00&0.00&1.00\tabularnewline
~~15k-\textless25k&1.52 (0.75-2.28)& 9,840&0.74&0.33&0.37\tabularnewline
~~25k-\textless35k&2.41 (0.84-3.97)& 4,850&1.39&0.45&0.46\tabularnewline
~~35k-\textless50k&0.69 (0.06-1.32)& 1,011&0.47&0.56&0.18\tabularnewline
~~50+k&1.22 (0.09-2.34)& 1,738&0.89&0.61&0.85\tabularnewline
\hline
{\bfseries Marital status}&&&&&\tabularnewline
~~Married&2.27 (1.65-2.90)&24,734&1.00&0.00&1.00\tabularnewline
~~Divorced&2.62 (1.49-3.75)&13,835&1.28&0.30&0.40\tabularnewline
~~Widowed&3.51 (2.12-4.90)&10,473&0.92&0.30&0.81\tabularnewline
~~Separated&0.43 (0.00-0.88)& 1,030&0.23&0.59&0.01\tabularnewline
~~Never Married&0.82 (0.16-1.48)& 4,031&1.72&0.43&0.20\tabularnewline
~~Unmarried Couple&0.48 (-0.0-1.02)&   800&0.47&0.63&0.24\tabularnewline
\hline
{\bfseries Employment status}&&&&&\tabularnewline
~~Employed&0.80 (0.38-1.22)& 9,054&1.00&0.00&1.00\tabularnewline
~~Out of work&0.91 (0.03-1.79)& 2,549&1.13&0.62&0.84\tabularnewline
~~Homework&1.55 (0.94-2.16)& 8,066&1.23&0.44&0.63\tabularnewline
~~Student&0 (0-0)&     0&0.00&0.62&0.00\tabularnewline
~~Retired&3.60 (2.49-4.71)&17,473&1.36&0.43&0.47\tabularnewline
~~Unable to work&7.91 (5.06-10.7)&17,763&5.50&0.44&0.00\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}

 

 
%latex.default(object = hrqol.tabl, title = "Variables", file = "",     append = TRUE, rgroup = c("Health perception", "Physical unhealthy",         "Mental unhealthy", "Activity limitation", "Physical and mental unhealthy"),     n.rgroup = c(2, 2, 2, 2, 2), rowname = c("Very Good", "Fair / Poor",         rep(c("0-13 days", "14 or more days"), 4)), table.env = T,     here = T, caption = paste(set_Measure, " among adults by health related quality of life variables,",         set_Years, sep = " "), label = "tab:hrqol.tabl")%
\begin{table}[H]
\caption{Stroke prevalence  among adults by health related quality of life variables, 2013\label{tab:hrqol.tabl}} 
\begin{center}
\begin{tabular}{llllll}
\hline\hline
\multicolumn{1}{l}{Variables}&\multicolumn{1}{c}{Prevalence}&\multicolumn{1}{c}{Number}&\multicolumn{1}{c}{OR}&\multicolumn{1}{c}{OR(SE)}&\multicolumn{1}{c}{p-value}\tabularnewline
\hline
{\bfseries Health perception}&&&&&\tabularnewline
~~Very Good&0.83 (0.53-1.14)&15,240&1.00&0.00&1.00\tabularnewline
~~Fair / Poor&3.99 (3.09-4.89)&39,665&0.95&0.32&0.88\tabularnewline
\hline
{\bfseries Physical unhealthy}&&&&&\tabularnewline
~~0-13 days&1.52 (1.15-1.88)&36,499&1.00&0.00&1.00\tabularnewline
~~14 or more days&4.32 (2.92-5.72)&17,680&0.96&0.38&0.92\tabularnewline
\hline
{\bfseries Mental unhealthy}&&&&&\tabularnewline
~~0-13 days&1.77 (1.39-2.14)&42,584&1.00&0.00&1.00\tabularnewline
~~14 or more days&2.88 (1.57-4.19)&11,224&0.57&0.42&0.19\tabularnewline
\hline
{\bfseries Activity limitation}&&&&&\tabularnewline
~~0-13 days&2.27 (1.58-2.95)&22,502&1.00&0.00&1.00\tabularnewline
~~14 or more days&3.97 (2.23-5.72)& 9,819&0.45&0.51&0.13\tabularnewline
\hline
{\bfseries Physical and mental unhealthy}&&&&&\tabularnewline
~~0-13 days&1.51 (1.13-1.88)&32,532&1.00&0.00&1.00\tabularnewline
~~14 or more days&3.37 (2.34-4.40)&22,372&0.85&0.30&0.60\tabularnewline
\hline
\end{tabular}\end{center}

\end{table}


